class ProductPage:
    ELEMENT = "//*[@id='form-product']/div/table/tbody/tr[4]/td[3]"
    ADD = " //*[@id='content']/div[1]/div/div/a"
    PRODUCT_NAME = "input#input-name1"
    NAME = "test_device2"
    META_NAME = "input#input-meta-title1"
    DATA_PAGE = "//*[@id='form-product']/ul/li[2]/a"
    MODEL = "TEST MODEL2"
    MODEL_NAME = "input#input-model"
    ADD_DEVICE = "button[type='submit']"
    LIST = "//*[@id='form-product']/div/table/tbody/tr/td[3]"
    EDIT = "//*[@id='form-product']/div/table/tbody/tr[4]/td[8]"
    NEW_NAME = "111"
    CHECKBOX = "//*[@id='form-product']/div/table/tbody/tr[20]/td[1]"
    DELETE = "//*[@id='content']/div[1]/div/div/button[3]"
